--
-- File generated with SQLiteStudio v3.4.4 on Thu Dec 21 09:59:19 2023
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: CONFIG
CREATE TABLE IF NOT EXISTS CONFIG (NAME TEXT PRIMARY KEY UNIQUE NOT NULL DEFAULT "", VALUE TEXT DEFAULT "");

-- Table: CREDENTIALS
CREATE TABLE IF NOT EXISTS CREDENTIALS (ID TEXT (128) PRIMARY KEY UNIQUE NOT NULL, PROVIDER_ID TEXT (128) UNIQUE NOT NULL REFERENCES PROVIDERS (ID), USERNAME TEXT NOT NULL, PASSWORD TEXT NOT NULL);

-- Table: PROVIDERS
CREATE TABLE IF NOT EXISTS PROVIDERS (ID TEXT (128) PRIMARY KEY UNIQUE NOT NULL, NAME TEXT (255) NOT NULL UNIQUE, ADDRESS TEXT NOT NULL, SELECTED NUMERIC (1) DEFAULT (0) CONSTRAINT SELECTED_VAL_CHECK CHECK (SELECTED == 0 OR SELECTED == 1) NOT NULL);

-- Trigger: SELECTED_PROVIDER_CONSTRAINT
CREATE TRIGGER IF NOT EXISTS SELECTED_PROVIDER_CONSTRAINT BEFORE UPDATE ON PROVIDERS WHEN new.SELECTED == 1  BEGIN UPDATE PROVIDERS SET SELECTED = 0 WHERE (ID != NEW.ID); END;

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
